### ISSUE TITLE
 Concerns regarding the experiment results

### ISSUE THREAD

**Issue by EallaChanHKU** [chenchongthu/EHCF#8]
In the experiment result, the proposed algorithms achieve about 50% improvement on the latest state of art baselines in multiple datasets, which raises concern. Usually, in recommendation works, a 10% improvement in metrics is already considered significant, the improvement described in the experiment just looks "too good to be true".

**Comment by chenchongthu** [comment]
Thank you for your question!  

Your concerns have been discussed in our paper ("Discussion on the Remarkable Improvements", page 5). Although sampling has been widely adopted in previous work, it is not very suitable for learning from multi-behavior data since it will produce very large randomness in total and can ignore many important instances. In existing work (e.g., NMTR and the most recent MBGCN), the use of auxiliary behavior data brings little improvement. While in our work, our EHCF outperforms EHCF-sin by 79.4% on Beibei and 108.8% on Taobao. Although NMTR and MBGCN are very new, their performances on multi behavior recommendation task are actually not very ideal. Existing sampling-based methods have not fully leveraged the auxiliary behavior data, which is also one of the major points of this work.

Moreover, if you have any concerns regarding the experiment results, you can also rerun the experiments by yourself. To get the codes of NMTR and MBGCN, you can contact the authors of the corresponding papers.

**Comment by EallaChanHKU** [comment]
Thank you.
